# Input/Output Paths
paths:
  output_dir: "pipeline_output"  # Thư mục chính để lưu tất cả các output

# Model Paths
models:
  # Đường dẫn đến các model weights (tương đối từ thư mục gốc)
  action_model: "weight/action/model-019-0.797827.pth"
  ball_action_model: "weight/ball/model-006-0.864002.pth"
  camera_model: "weight/camera/model_last.pth.tar"

# Ball Action & Action Model Parameters
ball_action_params:
  gpu_id: 0
  batch_size: 3
  target_fps: 25.0

# Camera Model Parameters
camera_params:
  gpu_id: 0
  fps: 2.0
  batch_size_feat: 128
  backend: "TF2"
  confidence_threshold: 0.2

# Rules Configuration
rules:
  config_path: "rules/config.yaml"  # Đường dẫn tương đối từ thư mục gốc
  limit: 80  # Số lượng highlight tối đa

# Video Clipping
clipping:
  # Thông số cho việc cắt video
  use_hardware_acceleration: true  # Sử dụng GPU để encode/decode video

